on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        env:
          USERNAME: ${{ inputs.username }}
          # token: ${{ secrets.token }}
        
        run: |
          echo $USERNAME
